version: "3"
services:
    web:
        build: .
        ports:
            - "8000:80"
    db:
        image: "mongo"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        ports:
            - 27017:27017
        volumes:
            - db-data:/mskh-sms

volumes: 
    db-data: